### ISSUE TITLE
cunn/SoftMax does not support images with 2^16 or more elements

### ISSUE THREAD

**Issue by jvlmdr** [torch/cunn#150]
The nn version works
```lua
model = nn.SoftMax()
x = torch.randn(1, 2, 65536, 1)
y = model:forward(x)
```
however the cunn version fails
```lua
model = model:cuda()
x = x:cuda()
y = model:forward(x)
```
with error
```
nngraph/gmodule.lua:281: invalid configuration argument at [...]/torch/extra/cunn/SoftMax.cu:153
```
This error does not occur when the image contains 65535 elements.

**Comment by hughperkins** [comment]
this is related to https://github.com/torch/cunn/issues/144 and https://github.com/torch/cunn/issues/148

**Comment by dan-sam** [comment]
I think this results from using a 2D grid of blocks to call the kernel where the first dimension of the grid is set by the batch size and the second dimension of the grid is set by multiplying the width and height of the "image" (more specifically, the width and height of the input when the SoftMax is computed across the depth).  Since there is a max size of 65535 (2^16 - 1) blocks per dimension in a grid, this caps the number of elements (i.e. width*height) at 65535.

This can be rectified by using a 3D grid of blocks and setting the 2nd/3rd dimension of the grid to the width/height of the image and then adding the 3rd dimension to the computation of the offset from the start of the input/output for each block. I have code that implements this but I think it will only work on GPUs with compute capability of 2.X or greater since the number of dimensions for a grid on a 1.X GPU is capped at 2. Also, I have only really tested that this solution works and have not tested that this solution is efficient.

The CPU spatial SoftMax code does not suffer from this maximum. So another solution is to copy the output from the from right before the Softmax to the CPU and compute the SoftMax on the CPU. Though not ideal, I have found this to be a workable solution in practice since the SoftMax is typically only used once at the end of a network (I think?) and does not make up a major portion of the computation.

**Comment by andreaskoepf** [comment]
'Table 13. Technical Specifications per Compute Capability' of the [Cuda Programming Guide](
http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#ixzz49EKnp7Yl) says
"Maximum y- or z-dimension of a grid of thread blocks 	65535".

@dmsammons I think your suggestion to use three dimensional blocks is a good idea. 

@soumith What is the minimum [compute capability](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities) that should be supported by cunn? '3D grid of thread blocks ' is available >= 3.X.

**Comment by andreaskoepf** [comment]
I created https://github.com/torch/cunn/pull/279.

**Comment by hughperkins** [comment]
> What is the minimum compute capability that should be supported by cunn? '3D grid of thread blocks ' is available >= 3.X.

Just in case it's useful, I checked the AWS K520s:
- they each contain two GK104s, see http://www.nvidia.co.uk/object/cloud-gaming-gpu-boards-uk.html
- a GK104 is compute capability 3.0, see https://en.wikipedia.org/wiki/CUDA

I doubt anyone is using anything much more ancient than these devices?

**Comment by soumith** [comment]
Fixed now in trunk
