### ISSUE TITLE
nn.Max does not support arbitraty dimensions

### ISSUE THREAD

**Issue by soumith** [torch/cunn#31]
right now the kernels we wrote only support the last dimension. 

p.s.: I'm treating any inconsistency with the CPU versions as bugs (as they rightly should be treated)

**Comment by DaniloRezende** [comment]
Is there any fix around this problem?

**Comment by dominikgrewe** [comment]
It seems like we can almost use standard Torch operations to implement this. The forward pass is a simple torch.max operation. In the backwards pass we need to copy the `gradOutput` values into `gradInput` at the max indices. This is vaguely similar to `maskedCopy`, but using one index per row instead of a mask. I don't think there's currently an operation like that in Torch. Would it be worthwhile adding it?

**Comment by soumith** [comment]
We have maskedCopy implemented, doing a PR soon. If the indices are linear indices for the whole tensor (viewed as 1D), maskedCopy seems enough

**Comment by szagoruyko** [comment]
can be closed
