### ISSUE TITLE
Test failures: VolumetricDilatedMaxPooling

### ISSUE THREAD

**Issue by borisfom** [torch/cunn#384]
Apparetly, test arithmetic around random sizes gets wrong intermittently:

VolumetricDilatedMaxPooling_forward_batch
 Function call failed
...omitchev/git/dgx/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #2 to 'v' (input image (T: 1 H: 81 W: 87) smaller than kernel size (kT: 3 kH: 2 kW: 3) at /home/bfomitchev/git/dgx/torch/extra/nn/lib/THNN/generic/VolumetricDilatedMaxPooling\
.c:157)
stack traceback:
        [C]: in function 'v'
        ...omitchev/git/dgx/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'VolumetricDilatedMaxPooling_updateOutput'
        ...install/share/lua/5.1/nn/VolumetricDilatedMaxPooling.lua:25: in function 'forward'
        ...itchev/git/dgx/torch/install/share/lua/5.1/cunn/test.lua:4502: in function 'v'
        ...itchev/git/dgx/torch/install/share/lua/5.1/cunn/test.lua:5671: in function <...itchev/git/dgx/torch/install/share/lua/5.1/cunn/test.lua:5669>
        [C]: in function 'xpcall'
        ...hev/git/dgx/torch/install/share/lua/5.1/torch/Tester.lua:477: in function '_pcall'
        ...hev/git/dgx/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
        ...hev/git/dgx/torch/install/share/lua/5.1/torch/Tester.lua:355: in function 'run'
        ...itchev/git/dgx/torch/install/share/lua/5.1/cunn/test.lua:5692: in function 'testcuda'
        [string "nn.testcuda()"]:1: in main chunk
        [C]: in function 'pcall'
        .../dgx/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406670

**Comment by gchanan** [comment]
Thanks for finding this!

I think for now we can just change the test to not generate cases where the input image is smaller than the kernel size.  I'll submit a pull request for that.

I did look into trying to generalize this a bit, because there are a number of tests that generate inputs in a similar way.  But this doesn't appear straightforward: e.g. SpatialAveragePooling checks that kernel size is <= input_size + 2 * padding (in nn), but SpatialMaxPooling checks that kernel size is <= image_size - padding (shouldn't this be 2 * padding?).  VolumetricAveragePooling doesn't allow specification of padding and VolumetricMaxPooling checks that kernel size is <= image_size (don't take padding into account).  Outside of SpatialMaxPooling, these seem to be correct checks given how the module is written.  This makes it pretty difficult to generate test cases that exercise the boundary conditions, though, and I assume to use these modules as well.

@soumith is there some logic behind the checks that I'm missing?  Is it worth filing an issue to try to to unify these?

**Comment by gchanan** [comment]
https://github.com/torch/cunn/pull/386 should fix the test issue.

**Comment by soumith** [comment]
@gchanan in general, there's potential for a HUGE refactor of cunn tests where 50% or more of the code can be templated properly. The size / bounds checks are common between almost all the Spatial modules, and similarly between all the pointwise / reduce operators. But the cost benefit of doing the refactor is quite low, and there are more pressing issue to work on.
