### ISSUE TITLE
nn.Max does not work under FP16 mode

### ISSUE THREAD

**Issue by shuzi** [torch/cunn#432]
![image](https://cloud.githubusercontent.com/assets/6613848/22438523/54abaac2-e6fa-11e6-9f5e-f02f9a1a1126.png)

**Comment by gchanan** [comment]
This looks like an issue with nn, not cunn.  I should be able to fix easily.

**Comment by fmassa** [comment]
@shuzi at least in your example, you forgot to convert the module to half type (using `:type ('torch.CudaHalfTensor')`

**Comment by gchanan** [comment]
@fmassa is correct of course, but even if you convert the type nn.Max will still fail.

There's a number of these issues where the Module checks for 'CudaTensor' type to figure out if it's a cuda module rather than any cuda tensor type.  Shouldn't be too hard to fix; I would just like a nice way of testing.

**Comment by gchanan** [comment]
https://github.com/torch/nn/pull/1124 should fix this.

**Comment by shuzi** [comment]
@gchanan 
The latest install still has the following error.

![image](https://cloud.githubusercontent.com/assets/6613848/22654710/b1bd0466-ec5b-11e6-8b74-bb051e9dae51.png)

**Comment by gchanan** [comment]
@shuzi did you update nn?  Here's results from updated nn and cunn:

th> nn.Max(1):type('torch.CudaHalfTensor'):forward(torch.CudaHalfTensor(10))
 0
[torch.CudaHalfTensor of size 1]

**Comment by shuzi** [comment]
@gchanan 

sorry it works now, my bad.
